import type { AlbumElement, BookState, ScrapbookPage } from '../domain/types'
import { AlbumPaper } from './AlbumPaper'
import { SpiralBinding } from './SpiralBinding'
import type { ReaderPaperTheme, ReaderViewMode } from './AlbumControls'

type GestureMode = 'move' | 'resize' | 'rotate'
type Props = { state: BookState; page: ScrapbookPage | null; leftPage?: ScrapbookPage | null; rightPage?: ScrapbookPage | null; bookmarkPage: number; viewerId?: string | null; selectedId?: string | null; editable?: boolean; revealAll?: boolean; viewMode: ReaderViewMode; paperTheme: ReaderPaperTheme; onBookmark: () => void; onPrevious: () => void; onNext: () => void; onSelect?: (pageId: string, id: string) => void; onLike?: (pageId: string, element: AlbumElement) => void; onElementPointerDown?: (event: React.PointerEvent<HTMLDivElement>, pageId: string, element: AlbumElement, mode: GestureMode) => void; direction: 'next' | 'previous' }

export function Scrapbook({ state, page, leftPage, rightPage, bookmarkPage, viewerId, selectedId, editable, revealAll, viewMode, paperTheme, onBookmark, onPrevious, onNext, onSelect, onLike, onElementPointerDown, direction }: Props) {
  const paper = (item: ScrapbookPage) => <AlbumPaper page={item} bookmarkPage={bookmarkPage} viewerId={viewerId} selectedId={selectedId} editable={editable} revealAll={revealAll} showBinding={false} onSelect={(id) => onSelect?.(item.id, id)} onLike={(element) => onLike?.(item.id, element)} onElementPointerDown={(event, element, mode) => onElementPointerDown?.(event, item.id, element, mode)} />
  const coverMessage = <span className="cover-hoshi-message"><i className="red-four-star" aria-hidden="true" /><b>Hoshi sigue brillando</b></span>
  if (state === 'CLOSED') return <button type="button" className="scrapbook-cover front-cover" onClick={onNext} aria-label="Abrir la libreta"><span className="cover-page-edge" aria-hidden="true" /><SpiralBinding cover /><span>BRATTYPOLITAN</span><strong>ARCHIVO<br />COLECTIVO</strong>{coverMessage}<span className="cover-mark"><img className="cover-emblem" src="/images/bratty-face-mark.png" alt="" /><b>星</b></span><span className="cover-bookmark" role="button" aria-label={`Ir a página ${bookmarkPage}`} onClick={(event) => { event.stopPropagation(); onBookmark() }}><i>{bookmarkPage}</i></span><small>clic para abrir</small></button>
  if (state === 'BACK_COVER') return <button type="button" className="scrapbook-cover back-cover" onClick={onPrevious} aria-label="Volver a la última hoja"><SpiralBinding cover /><span>FIN DEL PRIMER VOLUMEN</span><strong>BRATTY<br />2026</strong>{coverMessage}</button>
  if (!page) return <div className="scrapbook-loading">Preparando las páginas…</div>
  if (viewMode === 'SINGLE') return <div key={`${state}-${page.id}`} className={`scrapbook-single scrapbook-theme-${paperTheme.toLowerCase()} is-turning turn-${direction}`}><div className="scrapbook-sheet scrapbook-sheet--single" role="button" tabIndex={0} aria-label={`Hoja ${page.pageNumber}. Toca el lado izquierdo para retroceder o el derecho para avanzar.`} onClick={(event) => { const bounds = event.currentTarget.getBoundingClientRect(); (event.clientX - bounds.left) < bounds.width / 2 ? onPrevious() : onNext() }} onKeyDown={(event) => { if (event.key === 'ArrowLeft') onPrevious(); if (event.key === 'ArrowRight') onNext() }}>{paper(page)}<span className="single-page-zone single-page-zone--previous" aria-hidden="true">←</span><span className="single-page-zone single-page-zone--next" aria-hidden="true">→</span></div></div>
  return <div key={`${state}-${leftPage?.id ?? 'cover'}-${rightPage?.id ?? 'blank'}`} className={`scrapbook-spread scrapbook-theme-${paperTheme.toLowerCase()} is-turning turn-${direction}${page.pageNumber === 1 ? ' is-opening' : ''}`}>
    <div className={`scrapbook-sheet scrapbook-sheet--left${leftPage ? '' : ' scrapbook-open-cover'}`} role="button" tabIndex={0} aria-label="Retroceder una hoja" onClick={onPrevious} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onPrevious() }}>{leftPage ? paper(leftPage) : <div className="open-cover-panel"><span>BRATTYPOLITAN · VOLUMEN 01</span>{coverMessage}<small>La historia comienza aquí</small></div>}</div>
    <div className="scrapbook-gutter" aria-hidden="true"><SpiralBinding /></div>
    <div className="scrapbook-sheet scrapbook-sheet--right" role="button" tabIndex={0} aria-label="Avanzar una hoja" onClick={onNext} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onNext() }}>{rightPage ? paper(rightPage) : <div className="album-paper blank-paper" />}</div>
    <span className="sheet-hint sheet-hint--left">← retroceder</span><span className="sheet-hint sheet-hint--right">avanzar →</span>
  </div>
}
