import { useEffect, useState, type ChangeEvent } from 'react'
import { Layout } from '../components/Layout'
import { readLocalParticipationSettings } from '../features/album/data/localParticipation'
import { type AlbumElementType, type AuthorIdentity } from '../features/album/domain/types'
import { readPendingSubmissions, writePendingSubmissions } from '../features/album/data/localModeration'
const MAX_IMAGE_BYTES = 5 * 1024 * 1024
const TYPES: { value: AlbumElementType; label: string }[] = [{ value: 'PHOTO', label: 'Foto' }, { value: 'POST_IT', label: 'Post-it' }, { value: 'STICKER', label: 'Sticker / emoji' }, { value: 'TEXT', label: 'Texto libre' }]
const participantId = () => `participant-${crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`}`
export function ContributePage() {
  const [open, setOpen] = useState(() => readLocalParticipationSettings().isOpen); const [type, setType] = useState<AlbumElementType>('PHOTO'); const [name, setName] = useState(''); const [age, setAge] = useState(''); const [content, setContent] = useState(''); const [pages, setPages] = useState<number[]>([1]); const [photo, setPhoto] = useState<{ data: string; size: number; mime: string } | null>(null); const [message, setMessage] = useState<string | null>(null)
  useEffect(() => { const refresh = () => setOpen(readLocalParticipationSettings().isOpen); window.addEventListener('brattypolitan-participation-change', refresh); return () => window.removeEventListener('brattypolitan-participation-change', refresh) }, [])
  const choosePhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/') || file.size > MAX_IMAGE_BYTES) { setMessage('Selecciona una imagen de máximo 5 MB.'); return }; const reader = new FileReader(); reader.onload = () => setPhoto({ data: String(reader.result), size: file.size, mime: file.type }); reader.readAsDataURL(file) }
  const toggle = (page: number) => setPages((current) => current.includes(page) ? current.filter((item) => item !== page) : current.length === 3 ? current : [...current, page])
  const save = async () => { if (!pages.length || (type === 'PHOTO' && !photo)) { setMessage('Añade la foto y selecciona entre una y tres páginas.'); return }; const author: AuthorIdentity = { participantId: participantId(), displayName: name || undefined, age: age ? Number(age) : undefined }; const id = crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`; writePendingSubmissions([...readPendingSubmissions(), { id, author, type, content: photo ? photo.data : content, media: photo ? { originalWidth: 0, originalHeight: 0, mimeType: photo.mime, fileSize: photo.size } : undefined, pageNumbers: pages, createdAt: new Date().toISOString() }]); setMessage(`Recuerdo enviado a revisión. ID: ${author.participantId}`); setContent(''); setPhoto(null) }
  return <Layout><section className="content-card contribution"><p className="eyebrow">ARCHIVO COLECTIVO · PRUEBA LOCAL</p><h1>Dejar un recuerdo</h1>{!open ? <p className="muted">La captura está cerrada por el equipo.</p> : <div className="contribution-form"><p>Tu envío recibirá un ID único y se guardará sólo en este navegador durante la prueba.</p><label>Nombre (opcional)<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Edad (opcional)<input type="number" min="1" max="120" value={age} onChange={(event) => setAge(event.target.value)} /></label><label>Tipo<select value={type} onChange={(event) => setType(event.target.value as AlbumElementType)}>{TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{type === 'PHOTO' ? <label>Foto · máximo 5 MB<input type="file" accept="image/*" onChange={choosePhoto} />{photo && <small>{(photo.size / 1024 / 1024).toFixed(2)} MB lista</small>}</label> : <label>{type === 'STICKER' ? 'Emoji / sticker' : 'Mensaje'}<textarea maxLength={280} value={content} onChange={(event) => setContent(event.target.value)} placeholder={type === 'STICKER' ? '✦ 💖 ⭐' : 'Escribe aquí…'} /></label>}<fieldset><legend>Guardar en hasta tres páginas</legend><div className="page-choice">{Array.from({ length: 100 }, (_, index) => index + 1).map((page) => <label key={page}><input type="checkbox" checked={pages.includes(page)} disabled={!pages.includes(page) && pages.length >= 3} onChange={() => toggle(page)} />{page}</label>)}</div></fieldset><button type="button" onClick={() => void save()}>Guardar en la libreta</button>{message && <p className="muted">{message}</p>}</div>}</section></Layout>
}
