import { Route, Routes } from 'react-router-dom'
import { AlbumPage } from '../pages/AlbumPage'
import { AdminPage } from '../pages/AdminPage'
import { AboutPage } from '../pages/AboutPage'
import { ContributePage } from '../pages/ContributePage'
import { HomePage } from '../pages/HomePage'
import { NotFoundPage } from '../pages/NotFoundPage'
import { ConstellationEditorPage } from '../features/constellation-editor/ConstellationEditorPage'
import { hasDevelopmentAccess } from '../features/access/developmentAccess'
import { AlbumEditorPage } from '../features/album/editor/AlbumEditorPage'
import { ExperienceHubPage } from '../pages/ExperienceHubPage'
import { WorkspacePage } from '../pages/WorkspacePage'
export function AppRoutes() { const canDevelop = hasDevelopmentAccess(); return <Routes><Route path="/" element={<HomePage />} /><Route path="/workspace" element={<WorkspacePage />} /><Route path="/explorar" element={<ExperienceHubPage />} /><Route path="/admin/experiencias" element={canDevelop ? <ExperienceHubPage admin /> : <NotFoundPage />} /><Route path="/about" element={<AboutPage />} /><Route path="/contribute" element={<ContributePage />} /><Route path="/album" element={<AlbumPage />} /><Route path="/admin" element={<AdminPage />} /><Route path="/constellation-editor" element={canDevelop ? <ConstellationEditorPage /> : <NotFoundPage />} /><Route path="/dev/album-editor" element={canDevelop ? <AlbumEditorPage /> : <NotFoundPage />} /><Route path="*" element={<NotFoundPage />} /></Routes> }
