import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { createSetlistTrack, readSetlistTracks, writeSetlistTracks, type SetlistTrack } from '../data/localSetlistCatalog'
import { resolveSetlistCoverUrl, setlistCatalogRepository } from '../repositories/SetlistCatalogRepository'

export function SetlistManagerPage() {
  const [tracks, setTracks] = useState<SetlistTrack[]>(readSetlistTracks)
  const [message, setMessage] = useState<string | null>(null)
  useEffect(() => setlistCatalogRepository.subscribe((remoteTracks) => { if (remoteTracks.length) { setTracks(remoteTracks); writeSetlistTracks(remoteTracks) } }, () => setMessage('No fue posible sincronizar el catálogo con Firebase. Se usará la copia local.')), [])
  const commit = async (next: SetlistTrack[]) => { setTracks(next); writeSetlistTracks(next); try { if (setlistCatalogRepository.usesFirebase) { await setlistCatalogRepository.save(next); setMessage('Catálogo publicado para todas las personas.') } else setMessage('Catálogo guardado sólo en este navegador.') } catch { setMessage('No fue posible publicar el catálogo. Revisa que tu cuenta sea administradora.') } }
  const addTrack = () => commit([...tracks, createSetlistTrack(`Track ${tracks.length + 1}`)])
  const updateTrack = (id: string, patch: Partial<SetlistTrack>) => commit(tracks.map((track) => track.id === id ? { ...track, ...patch } : track))
  const removeTrack = (id: string) => commit(tracks.filter((track) => track.id !== id))
  return <main className="setlist-manager-page"><header className="album-editor-header"><div><p>HERRAMIENTA INTERNA · DESARROLLO</p><h1>Setlist Manager</h1></div><Link to="/dev/album-editor">Volver a la libreta</Link></header><section className="setlist-manager-intro"><p>Nombra las canciones y pega la ruta de su portada en GitHub, por ejemplo <code>/images/tracks/delusion.jpg</code>. El catálogo se publica en Firebase y la imagen se lee desde GitHub.</p><button type="button" onClick={addTrack}>+ Añadir track</button>{message && <small>{message}</small>}</section><section className="setlist-manager-grid">{tracks.map((track, index) => <article key={track.id}><div className="setlist-cover">{track.coverUrl ? <img src={resolveSetlistCoverUrl(track.coverUrl)} alt={`Portada de ${track.title}`} /> : <span>{String(index + 1).padStart(2, '0')}</span>}</div><label>Título<input value={track.title} onChange={(event) => void updateTrack(track.id, { title: event.target.value })} /></label><label>Ruta de portada en GitHub<input type="text" value={track.coverUrl ?? ''} placeholder="/images/tracks/mi-portada.jpg" onChange={(event) => void updateTrack(track.id, { coverUrl: event.target.value.trim() || undefined })} /></label><button type="button" className="setlist-delete" onClick={() => void removeTrack(track.id)}>Eliminar</button></article>)}</section>{!tracks.length && <p className="setlist-empty">Aún no hay tracks. Añade los que quieras poner a disposición de las personas.</p>}</main>
}
