import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './app/App'
import './styles/global.css'
import './styles/landing-m1.css'
import './styles/constellation-editor.css'
import './styles/album.css'
import './styles/experience-hub.css'
import './styles/workspace.css'
import './styles/news.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
